spring:
  application:
    name: CourseCrafter\

  datasource:
    url: jdbc:postgresql://localhost:5432/coursecrafter
    username: ${COURSE_CRAFTER_LOGIN} # read from env-var
    password: ${COURSE_CRAFTER_PASS} # read from env-var
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update        # dev-friendly: creates tables if missing

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1
      embedding:
        options:
          # Default model: text-embedding-ada-002
          model: text-embedding-3-small
    vectorstore:
      pgvector:
        initialize-schema: false

git:
  repo:
    root: /Users/igorwaraxe/ClaudeCode/CourseUpdater/course-material-repo/BasicAiCourse
    remote: origin
    defaultBranch: main
  auth:
    githubToken: ${GITHUB_PAT}   # read from env-var

# Database Import Configuration
coursecrafter:
  import:
    # Enable/disable database import functionality
    # Set to true to perform the first-time import of lecture content
    enabled: false
    # Override default import folder location (optional)
    folder: course_content

logging:
  level:
    com.coherentsolutions.coursecrafter.application.api.ai: DEBUG
    com.coherentsolutions.coursecrafter.application.service: DEBUG
    com.coherentsolutions.coursecrafter.domain.content.service: DEBUG
    # org.springframework.ai: DEBUG  # Optional: see Spring AI internals